/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as PaketIndexRouteImport } from './routes/paket/index'
import { Route as LocationIndexRouteImport } from './routes/location/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as WorkWorkIdRouteImport } from './routes/work/$workId'
import { Route as LocationLocationIdRouteImport } from './routes/location/$locationId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketIndexRoute = PaketIndexRouteImport.update({
  id: '/paket/',
  path: '/paket/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIndexRoute = LocationIndexRouteImport.update({
  id: '/location/',
  path: '/location/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWorkIdRoute = WorkWorkIdRouteImport.update({
  id: '/work/$workId',
  path: '/work/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationLocationIdRoute = LocationLocationIdRouteImport.update({
  id: '/location/$locationId',
  path: '/location/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/location/$locationId': typeof LocationLocationIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/blog/': typeof BlogIndexRoute
  '/location/': typeof LocationIndexRoute
  '/paket/': typeof PaketIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/location/$locationId': typeof LocationLocationIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/blog': typeof BlogIndexRoute
  '/location': typeof LocationIndexRoute
  '/paket': typeof PaketIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/location/$locationId': typeof LocationLocationIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/blog/': typeof BlogIndexRoute
  '/location/': typeof LocationIndexRoute
  '/paket/': typeof PaketIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/location/$locationId'
    | '/work/$workId'
    | '/blog/'
    | '/location/'
    | '/paket/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/location/$locationId'
    | '/work/$workId'
    | '/blog'
    | '/location'
    | '/paket'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/location/$locationId'
    | '/work/$workId'
    | '/blog/'
    | '/location/'
    | '/paket/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LocationLocationIdRoute: typeof LocationLocationIdRoute
  WorkWorkIdRoute: typeof WorkWorkIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LocationIndexRoute: typeof LocationIndexRoute
  PaketIndexRoute: typeof PaketIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paket/': {
      id: '/paket/'
      path: '/paket'
      fullPath: '/paket/'
      preLoaderRoute: typeof PaketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/': {
      id: '/location/'
      path: '/location'
      fullPath: '/location/'
      preLoaderRoute: typeof LocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$workId': {
      id: '/work/$workId'
      path: '/work/$workId'
      fullPath: '/work/$workId'
      preLoaderRoute: typeof WorkWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$locationId': {
      id: '/location/$locationId'
      path: '/location/$locationId'
      fullPath: '/location/$locationId'
      preLoaderRoute: typeof LocationLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  LocationLocationIdRoute: LocationLocationIdRoute,
  WorkWorkIdRoute: WorkWorkIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  LocationIndexRoute: LocationIndexRoute,
  PaketIndexRoute: PaketIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
